name: PicoLimboBridge
version: 1.0.0-SNAPSHOT
main: github.vanes430.picolimbobridge.spigot.PicoLimboBridgeSpigot
api-version: 1.20
folia-supported: true
author: vanes430
commands:
  picolimbo:
    description: Manage the PicoLimbo process
    usage: /picolimbo <start [port]|stop|reinstall [force]>
    permission: picolimbobridge.admin
